const PIN='hhc2026';
const $=id=>document.getElementById(id);
let state={title:'헥토헬스케어 이벤트 추첨',names:[],winner:'',winMsg:'축하합니다! 당첨되었습니다.',loseMsg:'아쉽지만 이번에는 미당첨입니다.'};
function login(){if($('pin').value===PIN){$('login').classList.add('hidden');$('app').classList.remove('hidden');sync();render();}else alert('PIN이 맞지 않습니다.');}
function names(){return [...new Set(($('names').value||'').split(/[\n\r,，、;\t]+/).map(v=>v.trim()).filter(Boolean))];}
function sync(){state.title=$('title').value.trim()||'헥토헬스케어 이벤트 추첨';state.names=names();state.winMsg=$('winMsg').value.trim()||'축하합니다! 당첨되었습니다.';state.loseMsg=$('loseMsg').value.trim()||'아쉽지만 이번에는 미당첨입니다.';if(state.winner&&!state.names.includes(state.winner))state.winner='';}
function enc(obj){return btoa(unescape(encodeURIComponent(JSON.stringify(obj)))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');}
function payload(){return {t:state.title,n:state.names,w:state.winner,wm:state.winMsg,lm:state.loseMsg};}
function base(){return location.href.replace(/index\.html.*$/,'').split('?')[0].split('#')[0];}
function resultLink(){return base()+'result.html?d='+enc(payload());}
function announceLink(){return base()+'announce.html?d='+enc(payload());}
function chipList(el,names){el.innerHTML='';names.forEach(n=>{const d=document.createElement('div');d.className='chip';d.textContent=n;d.dataset.name=n;el.appendChild(d);});}
function render(){sync();$('stageTitle').textContent=state.title;$('count').textContent='참여자 '+state.names.length+'명';$('winnerPill').textContent=state.winner?'당첨자: '+state.winner:'당첨자 미선정';chipList($('chips'),state.names);$('resultUrl').value=resultLink();$('announceUrl').value=announceLink();if(state.winner)setResult(state.winner,state.winMsg,true);else setResult('대기 중','추첨을 시작하면 당첨자가 표시됩니다.',null);}
function setResult(name,msg,isWin){$('result').innerHTML='<div class="resultLabel">RESULT</div><div class="winnerName">'+esc(name)+'</div><div class="message '+(isWin?'win':isWin===false?'lose':'')+'">'+esc(msg)+'</div>';}
function esc(s){return String(s).replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]));}
function clear(){document.querySelectorAll('.chip').forEach(c=>c.classList.remove('spin','winner','loser'));}
function animate(finalName,done){const chips=[...document.querySelectorAll('.chip')];clear();let i=0,rounds=Math.min(70,Math.max(28,chips.length*2)),delay=36;function tick(){chips.forEach(c=>c.classList.remove('spin'));chips[i%chips.length]?.classList.add('spin');i++;delay+=4;if(i<rounds)setTimeout(tick,delay);else{chips.forEach(c=>{c.classList.remove('spin'); if(c.dataset.name===finalName)c.classList.add('winner'); else c.classList.add('loser')});done&&done();}}tick();}
function draw(){sync();if(!state.names.length){alert('참여자를 입력해주세요.');return}state.winner=state.names[Math.floor(Math.random()*state.names.length)];render();setResult('추첨 중','후보자를 확인하고 있습니다.',null);animate(state.winner,()=>{setResult(state.winner,state.winMsg,true);$('winnerPill').textContent='당첨자: '+state.winner;confetti();$('resultUrl').value=resultLink();$('announceUrl').value=announceLink();});}
function resetAll(){state.winner='';render();}
function copy(id){const v=$(id).value;navigator.clipboard?.writeText(v).then(()=>alert('복사했습니다.')).catch(()=>{$(id).select();document.execCommand('copy');alert('복사했습니다.')});}
function openAnnounce(){if(!state.winner){alert('먼저 추첨을 진행해주세요.');return}window.open(announceLink(),'_blank');}
function confetti(){const box=$('confetti');box.innerHTML='';for(let i=0;i<80;i++){const p=document.createElement('i');p.style.left=Math.random()*100+'%';p.style.top=(-30-Math.random()*140)+'px';p.style.background=['#ff5a00','#facc15','#22c55e','#60a5fa','#f472b6'][Math.floor(Math.random()*5)];p.style.animationDelay=(Math.random()*.45)+'s';box.appendChild(p)}setTimeout(()=>box.innerHTML='',2200)}
function drawCard(ctx,t,w,msg,frame=0){const W=1280,H=720;ctx.clearRect(0,0,W,H);let g=ctx.createLinearGradient(0,0,W,H);g.addColorStop(0,'#351c0f');g.addColorStop(.55,'#111827');g.addColorStop(1,'#07080c');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.fillStyle='rgba(255,255,255,.08)';for(let i=0;i<40;i++){ctx.beginPath();ctx.arc((i*97+frame*6)%W,(i*53+frame*3)%H,3+(i%5),0,Math.PI*2);ctx.fill();}ctx.fillStyle='#ffedd5';ctx.font='800 52px Malgun Gothic';ctx.textAlign='center';ctx.fillText('🎉 당첨자 발표',W/2,135);ctx.fillStyle='#cbd5e1';ctx.font='700 30px Malgun Gothic';ctx.fillText(t,W/2,190);ctx.fillStyle='#facc15';ctx.font='900 110px Malgun Gothic';ctx.fillText(w,W/2,370);ctx.fillStyle='#bbf7d0';ctx.font='800 42px Malgun Gothic';ctx.fillText(msg,W/2,460);ctx.fillStyle='#9aa3b2';ctx.font='600 24px Malgun Gothic';ctx.fillText('헥토헬스케어 이벤트 추첨',W/2,610);}
function downloadPng(){if(!state.winner){alert('먼저 추첨을 진행해주세요.');return}const c=$('recordCanvas'),ctx=c.getContext('2d');drawCard(ctx,state.title,state.winner,state.winMsg,0);const a=document.createElement('a');a.href=c.toDataURL('image/png');a.download='hecto_lottery_winner.png';a.click();}
async function downloadWebm(){if(!state.winner){alert('먼저 추첨을 진행해주세요.');return}const c=$('recordCanvas'),ctx=c.getContext('2d');const stream=c.captureStream(30);const rec=new MediaRecorder(stream,{mimeType:'video/webm'});const chunks=[];rec.ondataavailable=e=>chunks.push(e.data);rec.onstop=()=>{const blob=new Blob(chunks,{type:'video/webm'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='hecto_lottery_winner.webm';a.click();};rec.start();let f=0;const timer=setInterval(()=>{drawCard(ctx,state.title,state.winner,state.winMsg,f++);},33);setTimeout(()=>{clearInterval(timer);rec.stop();},4200);}
['title','names','winMsg','loseMsg'].forEach(id=>setTimeout(()=>$(id)?.addEventListener('input',render),0));
window.addEventListener('load',()=>{sync();render();});
